/**
 * Reads the rail stop set derived from the Prasarana GTFS static feed.
 *
 * The source extract is generated by `node scripts/build-rail-stops.mjs`, imported into
 * PostgreSQL, and delivered by FastAPI in the application bootstrap payload. Nothing
 * here parses GTFS or reads a bundled JSON file at runtime.
 *
 * Positions come from the feed's stop_lat / stop_lon only. The feed also carries a
 * `geometry` column serialised as the literal string "[object Object]"; the build script
 * never reads it and neither does this module (AC 1.1.1).
 */

import { databaseData } from '../databaseData';

/** One station. Platform rows sharing a name and location are merged into a single entry. */
export interface RailStop {
  stopId: string;
  /** Exact feed stop_name, whitespace-normalised. */
  name: string;
  lat: number;
  lon: number;
  /** route_ids of every line serving this station. */
  lines: string[];
  /** The feed stop_ids merged into this station, one per line. */
  platforms: string[];
}

export interface RailFrequencyWindow {
  serviceId: string;
  startTime: string;
  endTime: string;
  headwaySeconds: number;
}

export interface RailFrequency {
  minHeadwaySeconds: number;
  maxHeadwaySeconds: number;
  windows: RailFrequencyWindow[];
}

export interface RailLine {
  routeId: string;
  shortName: string;
  longName: string;
  mode: string;
  color: string;
  stopCount: number;

  /**
   * Published GTFS headway information.
   * Null when the feed provides no frequency data for this route.
   */
  frequency: RailFrequency | null;
}

export interface ServiceCalendar {
  serviceId: string;
  days: string[];
  startDate: string;
  endDate: string;
  referencedByTrips: boolean;
  expired: boolean;
}

export interface RailFeed {
  feedId: string;
  feedName: string;
  agency: string;
  source: string;
  licence: string | null;
  licenceStatus: string;
  serviceDateRange: { start: string; end: string };
  serviceCalendars: ServiceCalendar[];
  lines: RailLine[];
}

export interface BoundingBox {
  minLat: number;
  maxLat: number;
  minLon: number;
  maxLon: number;
}

export interface RailFeedMetadata {
  feeds: RailFeed[];
  /** Each line Epic 1 names, and whether this feed actually contains it. */
  epicLineCoverage: { label: string; routeId: string; present: boolean }[];
  /** Modes absent from the computation, named verbatim for display (AC 1.3.3). */
  modesNotLoaded: string[];
  /** Extent of the loaded stops. The basis for the study area (AC 1.1.2). */
  studyAreaFeedExtent: BoundingBox;
  notes: string[];
  warnings: string[];
}

/** Every station in the loaded feed. */
export function loadRailStops(): RailStop[] {
  return databaseData().railStops as RailStop[];
}

/** Feed provenance, service periods, line coverage and the modes left out. */
export function loadRailFeedMetadata(): RailFeedMetadata {
  return databaseData().railMetadata as RailFeedMetadata;
}

/** Resolves a stop's route_ids to the lines serving it, for display. */
export function linesForStop(stop: RailStop): RailLine[] {
  const linesByRouteId = new Map(
    loadRailFeedMetadata().feeds.flatMap(feed => feed.lines).map(line => [line.routeId, line]),
  );
  return stop.lines
    .map(routeId => linesByRouteId.get(routeId))
    .filter((line): line is RailLine => line !== undefined);
}

/**
 * Converts the GTFS route metadata into a rider-facing mode label.
 *
 * The label is inferred only from the published line name; it does not
 * affect routing.
 */
export function displayModeForLine(
  line: RailLine,
): string {
  const name =
    `${line.shortName} ${line.longName}`.toUpperCase();

  if (name.includes('BRT')) return 'BRT';
  if (name.includes('MRT')) return 'MRT';
  if (name.includes('LRT')) return 'LRT';
  if (name.includes('MONORAIL')) return 'Monorail';

  return line.mode;
}

/**
 * AC 3.2.1 — rider-facing frequency from published GTFS headways.
 *
 * This is a service-frequency range, not a predicted waiting time.
 */
export function formatLineFrequency(
  line: RailLine,
): string {
  if (!line.frequency) {
    return 'Frequency unavailable';
  }

  const minMinutes =
    line.frequency.minHeadwaySeconds / 60;

  const maxMinutes =
    line.frequency.maxHeadwaySeconds / 60;

  const formatMinutes = (minutes: number) =>
    Number.isInteger(minutes)
      ? minutes.toString()
      : minutes.toFixed(1);

  if (minMinutes === maxMinutes) {
    return `Every ${formatMinutes(minMinutes)} min`;
  }

  return `Every ${formatMinutes(minMinutes)}–${formatMinutes(maxMinutes)} min`;
}
