/**
 * Reads the searchable named-place set derived from OpenStreetMap.
 *
 * The JSON in ../places/ is generated by `node scripts/build-places.mjs` and committed.
 * Nothing here queries a service and nothing fetches over the network — the data is a
 * static import, so the browser makes no request for it.
 *
 * This is what lets the search field accept a suburb, a mall or a hospital and not only a
 * station, WITHOUT calling a geocoder. AC 1.1.3 forbids the application calling an
 * external geocoding endpoint, and the Epic 1 Definition of Done repeats it. Both hold
 * because the lookup happened once, at build time, in the script — not here, and not on
 * any keystroke.
 *
 * Do not add a live lookup to this module or to anything that consumes it. If a place is
 * missing, re-run the build script and commit the result; that is the supported path.
 * A "helpful" Nominatim fallback would silently break a criterion the team has already
 * had to defend, and would send every user's query to a third party.
 */

import placesDoc from '../places/places.json';

/** Coarse category, used to label a result row so two same-named places are tellable apart. */
export type PlaceKind =
  | 'city'
  | 'town'
  | 'suburb'
  | 'hospital'
  | 'university'
  | 'mall'
  | 'attraction'
  | 'airport';

export interface OsmPlace {
  /** OSM element id, prefixed by type: "n254073469". Stable enough to use as a React key. */
  placeId: string;
  /** The OSM `name` tag, whitespace-normalised. */
  name: string;
  kind: PlaceKind;
  /** Human-readable form of `kind`, e.g. "Shopping mall". Shown in the result row. */
  kindLabel: string;
  lat: number;
  lon: number;
}

export interface PlacesMetadata {
  generatedAt: string;
  source: string;
  licence: string;
  placeCount: number;
}

const PLACES = placesDoc.places as OsmPlace[];

/** Every named place in the committed extract. */
export function loadPlaces(): OsmPlace[] {
  return PLACES;
}

/** Provenance of the place extract, for attribution and staleness checks. */
export function loadPlacesMetadata(): PlacesMetadata {
  return {
    generatedAt: placesDoc.generatedAt,
    source: placesDoc.source,
    licence: placesDoc.licence,
    placeCount: placesDoc.placeCount,
  };
}
