/**
 * Reads the searchable named-place set derived from OpenStreetMap.
 *
 * The source extract is generated by `node scripts/build-places.mjs`, imported into
 * PostgreSQL, and delivered by the project's FastAPI bootstrap endpoint. Search remains
 * local in the browser after that one application-data request.
 *
 * This is what lets the search field accept a suburb, a mall or a hospital and not only a
 * station, WITHOUT calling a geocoder. AC 1.1.3 forbids the application calling an
 * external geocoding endpoint, and the Epic 1 Definition of Done repeats it. Both hold
 * because the lookup happened during ingestion, not on any search keystroke.
 *
 * Do not add a live lookup to this module or to anything that consumes it. If a place is
 * missing, re-run the build script and commit the result; that is the supported path.
 * A "helpful" Nominatim fallback would silently break a criterion the team has already
 * had to defend, and would send every user's query to a third party.
 */

import { databaseData } from '../databaseData';

/** Coarse category, used to label a result row so two same-named places are tellable apart. */
export type PlaceKind =
  | 'city'
  | 'town'
  | 'suburb'
  | 'hospital'
  | 'university'
  | 'mall'
  | 'attraction'
  | 'airport';

export interface OsmPlace {
  /** OSM element id, prefixed by type: "n254073469". Stable enough to use as a React key. */
  placeId: string;
  /** The OSM `name` tag, whitespace-normalised. */
  name: string;
  kind: PlaceKind;
  /** Human-readable form of `kind`, e.g. "Shopping mall". Shown in the result row. */
  kindLabel: string;
  lat: number;
  lon: number;
}

export interface PlacesMetadata {
  generatedAt: string;
  source: string;
  licence: string;
  placeCount: number;
}

/** Every named place loaded from PostgreSQL through FastAPI. */
export function loadPlaces(): OsmPlace[] {
  return databaseData().places as OsmPlace[];
}

/** Provenance of the place extract, for attribution and staleness checks. */
export function loadPlacesMetadata(): PlacesMetadata {
  return databaseData().placesMetadata as PlacesMetadata;
}
